version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: dicri-sqlserver
    restart: unless-stopped
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=DicriPass2024!
      - MSSQL_PID=Express
    volumes:
      - sqlserver-data:/var/opt/mssql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - dicri-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dicri-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_SERVER=sqlserver
      - DB_DATABASE=Prueba_Tec
      - DB_USER=sa
      - DB_PASSWORD=DicriPass2024!
      - DB_PORT=1433
      - JWT_SECRET=dicri_secret_2024_production_key_change_this
      - JWT_EXPIRES_IN=24h
    networks:
      - dicri-network
    depends_on:
      - sqlserver

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dicri-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - dicri-network
    depends_on:
      - backend

networks:
  dicri-network:
    driver: bridge

volumes:
  sqlserver-data: